# Proxy to use for all Twitter connections.
proxy: null
# Alternative to proxy: an HTTP endpoint that returns the proxy URL to use for Twitter connections.
get_proxy_url: null

# Displayname template for Twitter users.
# {{ .DisplayName }} is replaced with the display name of the Twitter user.
# {{ .Username }} is replaced with the username of the Twitter user.
displayname_template: "{{ .DisplayName }} (Twitter)"

# Maximum number of conversations to sync on startup
conversation_sync_limit: 20
